import { montserrat, poppins } from "@/helpers/fonts";
import "../global.scss";

export const metadata = {
	title: {
		template: "%s | Cosmo Shop",
		default: "Cosmo Shop",
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${montserrat.variable} ${poppins.variable}`}
		>
			<body
				suppressHydrationWarning={true}
				className={`d-flex flex-column justify-content-between vh-100`}
			>
				{children}
			</body>
		</html>
	);
}
